### ISSUE TITLE
Carousel not working as intended especially next btn

### ISSUE THREAD

**Issue by thekiranmahajan** [thekiranmahajan/tandoori-js#1]
I want that Carousel to stop at the last image but the condition of moveNext depends upon the carouselCards.length which is 20 but images getting scrolled based on the offsetWidth of the carousel div of images.
issues is in the Carousel.jsx

**Comment by arvindpndit** [comment]
Try this and let me whether it works or not.

`import React, { useState, useEffect, useRef } from "react";
import { CARD_URL } from "../constants";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faArrowLeft, faArrowRight } from "@fortawesome/free-solid-svg-icons";

const Carousel = ({ carouselCards }) => {
  if (!carouselCards) return null; // when api call on small screens remove Carousel
  const carousel = useRef(null);
  const [currentIndex, setCurrentIndex] = useState(0);

  const movePrev = () => {
    if (currentIndex > 0) {
      setCurrentIndex((prevIndex) => prevIndex - 1);
    }
  };

  const moveNext = () => {
    const maxIndex = Math.floor(carousel.current.scrollWidth / carousel.current.offsetWidth) - 1;

    if (currentIndex < maxIndex) {
      setCurrentIndex((prevIndex) => prevIndex + 1);
    }
  };

  useEffect(() => {
    if (carousel.current !== null) {
      carousel.current.scrollLeft = carousel.current.offsetWidth * currentIndex;
    }
  }, [currentIndex]);

  return (
    <div className="w-11/12 h-64 flex flex-col mt-10">
      <div className="flex items-center justify-between w-full">
        <h3 className="font-bold text-xl pl-4 p-5">What's on your mind?</h3>
        <div className="flex gap-4">
          <button
            onClick={movePrev}
            className="h-10 w-10 text-center rounded-full bg-white flex items-center justify-center cursor-pointer hover:scale-90 transition-all duration-200 drop-shadow-xl focus:ring-4 ring-green-400 active:scale-105 disabled:opacity-25 disabled:cursor-not-allowed"
            disabled={currentIndex === 0}
          >
            <FontAwesomeIcon icon={faArrowLeft} />
          </button>
          <button
            onClick={moveNext}
            className="h-10 w-10 text-center rounded-full bg-white flex items-center justify-center cursor-pointer hover:scale-90 transition-all duration-200 drop-shadow-xl focus:ring-4 ring-green-400 active:scale-105 disabled:opacity-25 disabled:cursor-not-allowed"
            disabled={currentIndex === Math.floor(carouselCards.length / carousel.current.offsetWidth)}
          >
            <FontAwesomeIcon icon={faArrowRight} />
          </button>
        </div>
      </div>
      <div className="w-full h-52 relative overflow-hidden">
        <div
          ref={carousel}
          className="h-full pl-5 flex gap-4 overflow-hidden scroll-smooth"
        >
          {carouselCards.map((carouselCard) => (
            <img
              key={carouselCard.id}
              className="object-center h-full w-52 transition-transform hover:scale-110 duration-200 mix-blend-multiply "
              src={CARD_URL + carouselCard.imageId}
              alt="card img"
            />
          ))}
        </div>
      </div>
    </div>
  );
};

export default Carousel;
`

**Comment by arvindpndit** [comment]
```
const moveNext = () => {
    const maxIndex = Math.floor(carousel.current.scrollWidth / carousel.current.offsetWidth) - 1;

    if (currentIndex < maxIndex) {
      setCurrentIndex((prevIndex) => prevIndex + 1);
    }
```

try this and let me know whether it works or not.

**Comment by thekiranmahajan** [comment]
> ```
> const moveNext = () => {
>     const maxIndex = Math.floor(carousel.current.scrollWidth / carousel.current.offsetWidth) - 1;
> 
>     if (currentIndex < maxIndex) {
>       setCurrentIndex((prevIndex) => prevIndex + 1);
>     }
> ```
> 
> try this and let me know whether it works or not.

Thanks @arvindpndit, btw with this code what will be the btn disabled condition? coz btn on a large screen{without opening console} is now only accessible once i.e. its not slide through all images, maybe the if part getting false too early

**Comment by thekiranmahajan** [comment]
Hey!!! @arvindpndit I kinda tweaked it and it worked bro thanks 😊
```javascript
  const [maxIndex, setMaxIndex] = useState(0);
const moveNext = () => {
    setMaxIndex(
      Math.floor(carousel.current.scrollWidth / carousel.current.offsetWidth) -
        1
    );
    console.log(maxIndex);
    if (currentIndex <= maxIndex) {
      setCurrentIndex((prevIndex) => prevIndex + 1);
    }
  };
// btn disabled condition --> disabled={currentIndex > maxIndex}
```
